services:
  - type: web
    name: m-devblog
    env: node
    plan: free
    buildCommand: yarn && NODE_ENV=production yarn build
    startCommand: yarn start
    healthCheckPath: /_health
    envVars:
      - key: PUBLIC_SERVER_URL
        sync: false
      - key: NODE_VERSION
        value: ~16.13.0
      - key: NODE_ENV
        value: production
      - key: GITHUB_TOKEN
        sync: false
      - key: CLOUDINARY_NAME
        sync: false
      - key: CLOUDINARY_KEY
        sync: false
      - key: CLOUDINARY_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: mdevblog-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: APP_KEYS
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true

databases:
  - name: mdevblog-db
    plan: free
